services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: workout_tracker
      POSTGRES_USER: ${DB_USERNAME:-workout_tracker}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-workout_tracker}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
